# Site settings
title: pixyzehn
email: civokjots10.pico@gmail.com
author: pixyzehn
description: ""
baseurl: ""
keywords: "iOS, objective-c, swift, cocoa, apple, xcode, app store, programming"
url: "http://pixyzehn.com"
timezone: "Asia/Tokyo"
twitter_username: pixyzehn
github_username: pixyzehn

links:
  repo: 'https://github.com/pixyzehn/pixyzehn.github.io'
  twitter: 'https://twitter.com/pixyzehn'
  github: 'https://github.com/pixyzehn'
  linkedin: 'https://www.linkedin.com/in/pixyzehn'

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 8
paginate_path: "/page/:num"

gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-gist

exclude: [vendor]
